// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoFEXculzg7ktn-16QZkD82HYJ-0mb1MI',
    appId: '1:255923225135:web:c2cd06b5fc50816c33bcda',
    messagingSenderId: '255923225135',
    projectId: 'tuankietapp-4a0d6',
    authDomain: 'tuankietapp-4a0d6.firebaseapp.com',
    storageBucket: 'tuankietapp-4a0d6.appspot.com',
    measurementId: 'G-6RNVRVY599',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMaX3m8qiaB87GdkJBrYyOJQiVwu-OQJk',
    appId: '1:255923225135:android:1b7e1bef8be9a0ea33bcda',
    messagingSenderId: '255923225135',
    projectId: 'tuankietapp-4a0d6',
    storageBucket: 'tuankietapp-4a0d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1n5qqtAwsvE_93R8fJj1NxAsSY5cd3lw',
    appId: '1:255923225135:ios:a5d7843b28754dac33bcda',
    messagingSenderId: '255923225135',
    projectId: 'tuankietapp-4a0d6',
    storageBucket: 'tuankietapp-4a0d6.appspot.com',
    iosBundleId: 'com.example.ecommerceadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1n5qqtAwsvE_93R8fJj1NxAsSY5cd3lw',
    appId: '1:255923225135:ios:a5d7843b28754dac33bcda',
    messagingSenderId: '255923225135',
    projectId: 'tuankietapp-4a0d6',
    storageBucket: 'tuankietapp-4a0d6.appspot.com',
    iosBundleId: 'com.example.ecommerceadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoFEXculzg7ktn-16QZkD82HYJ-0mb1MI',
    appId: '1:255923225135:web:c2cd06b5fc50816c33bcda',
    messagingSenderId: '255923225135',
    projectId: 'tuankietapp-4a0d6',
    authDomain: 'tuankietapp-4a0d6.firebaseapp.com',
    storageBucket: 'tuankietapp-4a0d6.appspot.com',
    measurementId: 'G-6RNVRVY599',
  );

}